trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  RG: 'RG_Manu_Coppens'
  subscriptionId: 'cc934d76-6d72-49cb-a908-81217ad4ae29'
  location: 'West Europe'

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Bicep files'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'My-Service-Connection'
          subscriptionId: '$(subscriptionId)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(RG)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: 'main.bicep'
          deploymentMode: 'Validation'
